# -*- coding: utf-8 -*-
"""JSON_to_csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cy4eqMQvWzeJYpBGynsP5-TX9AsQOf13
"""

from google.colab import files
file = files.upload()

# Opening JSON file and loading the data
# into the variable data_json

import json

data = next(iter(file.values()))
type(data)

data_json = json.loads(data.decode())

data_json

import csv
  
# now we will open a file for writing
data_file = open('data_file.csv', 'w')
  
# create the csv writer object
csv_writer = csv.writer(data_file)
  
# Counter variable used for writing 
# headers to the CSV file
count = 0
  
for emp in data_json:
    if count == 0:
  
        # Writing headers of CSV file
        header = emp.keys()
        csv_writer.writerow(header)
        count += 1
  
    # Writing data of CSV file
    csv_writer.writerow(emp.values())
  
data_file.close()

df = pd.read_csv('data_file.csv', encoding='UTF-8')
df.head()

